function BER = runPlutoradioUniversalReceiver(prmUniversalReceiver, printData, samplenum) %#ok<INUSD>
%RUNPLUTORADIOUNIVERSALRECEIVER Receive frames using the ADALM-PLUTO radio.
%
%   This function is a modulation-agnostic counterpart of
%   runPlutoradioQPSKReceiver.
%
% Copyright 2017-2023 The MathWorks, Inc.

persistent rx radio
if isempty(rx)
    rx  = UniversalReceiver(...
        'ModulationOrder',                      prmUniversalReceiver.ModulationOrder, ...
        'SampleRate',                           prmUniversalReceiver.Fs, ...
        'DecimationFactor',                     prmUniversalReceiver.Decimation, ...
        'FrameSize',                            prmUniversalReceiver.FrameSize, ...
        'HeaderLength',                         prmUniversalReceiver.HeaderLength, ...
        'NumberOfMessage',                      prmUniversalReceiver.NumberOfMessage, ...
        'PayloadLength',                        prmUniversalReceiver.PayloadLength, ...
        'DesiredPower',                         prmUniversalReceiver.DesiredPower, ...
        'AveragingLength',                      prmUniversalReceiver.AveragingLength, ...
        'MaxPowerGain',                         prmUniversalReceiver.MaxPowerGain, ...
        'RolloffFactor',                        prmUniversalReceiver.RolloffFactor, ...
        'RaisedCosineFilterSpan',               prmUniversalReceiver.RaisedCosineFilterSpan, ...
        'InputSamplesPerSymbol',                prmUniversalReceiver.Interpolation, ...
        'MaximumFrequencyOffset',               prmUniversalReceiver.MaximumFrequencyOffset, ...
        'PostFilterOversampling',               prmUniversalReceiver.Interpolation/prmUniversalReceiver.Decimation, ...
        'PhaseRecoveryLoopBandwidth',           prmUniversalReceiver.PhaseRecoveryLoopBandwidth, ...
        'PhaseRecoveryDampingFactor',           prmUniversalReceiver.PhaseRecoveryDampingFactor, ...
        'TimingRecoveryDampingFactor',          prmUniversalReceiver.TimingRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth',          prmUniversalReceiver.TimingRecoveryLoopBandwidth, ...
        'TimingErrorDetectorGain',              prmUniversalReceiver.TimingErrorDetectorGain, ...
        'PreambleDetectionThreshold',           prmUniversalReceiver.PreambleDetectionThreshold, ...
        'DescramblerBase',                      prmUniversalReceiver.ScramblerBase, ...
        'DescramblerPolynomial',                prmUniversalReceiver.ScramblerPolynomial, ...
        'DescramblerInitialConditions',         prmUniversalReceiver.ScramblerInitialConditions, ...
        'BerMask',                              prmUniversalReceiver.BerMask, ...
        'PrintOption',                          printData, ...
        'Preview',                              prmUniversalReceiver.Preview);

    radio = sdrrx('Pluto');
    radio.RadioID               = prmUniversalReceiver.Address;
    radio.CenterFrequency       = prmUniversalReceiver.PlutoCenterFrequency;
    radio.BasebandSampleRate    = prmUniversalReceiver.PlutoFrontEndSampleRate;
    radio.SamplesPerFrame       = prmUniversalReceiver.PlutoFrameLength;
    radio.GainSource            = 'Manual';
    radio.Gain                  = prmUniversalReceiver.PlutoGain;
    radio.OutputDataType        = 'double';
end

currentTime = 0;
BER = [];
num_frames = floor(prmUniversalReceiver.StopTime*radio.BasebandSampleRate/radio.SamplesPerFrame);
rcvdSignal = complex(zeros(prmUniversalReceiver.PlutoFrameLength, num_frames));

cnt = 1;
while currentTime <  prmUniversalReceiver.StopTime && cnt<=num_frames
    rcvdSignal(:,cnt) = radio();
    [~, ~, ~, BER] = rx(rcvdSignal(:,cnt));
    currentTime=currentTime+(radio.SamplesPerFrame / radio.BasebandSampleRate);
    cnt = cnt+1;
end

release(rx);
release(radio);

end
