function BER = runPlutoradioQPSKReceiver(prmQPSKReceiver, printData, samplenum)

%   Copyright 2017-2022 The MathWorks, Inc.

persistent rx radio;
if isempty(rx)
    rx  = QPSKReceiver(...
        'ModulationOrder',                      prmQPSKReceiver.ModulationOrder, ...
        'SampleRate',                           prmQPSKReceiver.Fs, ...
        'DecimationFactor',                     prmQPSKReceiver.Decimation, ...
        'FrameSize',                            prmQPSKReceiver.FrameSize, ...
        'HeaderLength',                         prmQPSKReceiver.HeaderLength, ...
        'NumberOfMessage',                      prmQPSKReceiver.NumberOfMessage, ...
        'PayloadLength',                        prmQPSKReceiver.PayloadLength, ...
        'DesiredPower',                         prmQPSKReceiver.DesiredPower, ...
        'AveragingLength',                      prmQPSKReceiver.AveragingLength, ...
        'MaxPowerGain',                         prmQPSKReceiver.MaxPowerGain, ...
        'RolloffFactor',                        prmQPSKReceiver.RolloffFactor, ...
        'RaisedCosineFilterSpan',               prmQPSKReceiver.RaisedCosineFilterSpan, ...
        'InputSamplesPerSymbol',                prmQPSKReceiver.Interpolation, ...
        'MaximumFrequencyOffset',               prmQPSKReceiver.MaximumFrequencyOffset, ...
        'PostFilterOversampling',               prmQPSKReceiver.Interpolation/prmQPSKReceiver.Decimation, ...
        'PhaseRecoveryLoopBandwidth',           prmQPSKReceiver.PhaseRecoveryLoopBandwidth, ...
        'PhaseRecoveryDampingFactor',           prmQPSKReceiver.PhaseRecoveryDampingFactor, ...
        'TimingRecoveryDampingFactor',          prmQPSKReceiver.TimingRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth',          prmQPSKReceiver.TimingRecoveryLoopBandwidth, ...
        'TimingErrorDetectorGain',              prmQPSKReceiver.TimingErrorDetectorGain, ...
        'PreambleDetectionThreshold',           prmQPSKReceiver.PreambleDetectionThreshold, ...
        'DescramblerBase',                      prmQPSKReceiver.ScramblerBase, ...
        'DescramblerPolynomial',                prmQPSKReceiver.ScramblerPolynomial, ...
        'DescramblerInitialConditions',         prmQPSKReceiver.ScramblerInitialConditions,...
        'BerMask',                              prmQPSKReceiver.BerMask, ...
        'PrintOption',                          printData);
    
    % Create and configure the Pluto System object.
    radio = sdrrx('Pluto');
    radio.RadioID               = prmQPSKReceiver.Address;
    radio.CenterFrequency       = prmQPSKReceiver.PlutoCenterFrequency;
    radio.BasebandSampleRate    = prmQPSKReceiver.PlutoFrontEndSampleRate;
    radio.SamplesPerFrame       = prmQPSKReceiver.PlutoFrameLength;
    radio.GainSource            = 'Manual';
    radio.Gain                  = prmQPSKReceiver.PlutoGain;
    radio.OutputDataType        = 'double';
end

% Initialize variables
currentTime = 0;
BER = [];
num_frames = floor(prmQPSKReceiver.StopTime*radio.BasebandSampleRate/radio.SamplesPerFrame)
rcvdSignal = complex(zeros(prmQPSKReceiver.PlutoFrameLength,1),num_frames);

cnt = 1;
while currentTime <  prmQPSKReceiver.StopTime && cnt<=num_frames
    
    rcvdSignal(:,cnt) = radio();   % Receive signal from the radio
    %load RxData_Rsym_200000_Mod_4_veryclose.mat rcvdSignal
    
    % Decode the received message
    [~, ~, ~, BER] = rx(rcvdSignal(:,cnt));
    
    % Update simulation time
    currentTime=currentTime+(radio.SamplesPerFrame / radio.BasebandSampleRate);
    cnt = cnt+1;
end

release(rx);
release(radio);

% filename = ['RxData_Rsym_' num2str(prmQPSKReceiver.Rsym) '_Mod_' num2str(prmQPSKReceiver.ModulationOrder) '_BER_' num2str(ceil(BER(1)*100)) '_sample_' num2str(samplenum) '_veryclose'];
% save(filename) 
