function logResults(p, ber)
S = struct(...
    'CenterFrequency', p.CenterFrequency, ...
    'SampleRate', p.SampleRate, ...
    'SymbolRate', p.SymbolRate, ...
    'ModulationOrder', p.ModulationOrder, ...
    'TxGain', p.TxGain, ...
    'RxGain', p.RxGain, ...
    'BER', ber, ...
    'Timestamp', datetime);

if isfile(p.BERFile)
    load(p.BERFile, 'results');
    results = [results; struct2table(S)];
else
    results = struct2table(S);
end
save(p.BERFile, 'results');
end
