function tx = setupPlutoTx(p)
%SETUPPLUTOTX Configure an ADALM-PLUTO transmitter for the experiment.

tx = sdrtx('Pluto', ...
    'CenterFrequency',    p.CenterFrequency, ...
    'BasebandSampleRate', p.SampleRate, ...
    'Gain',               p.TxGain);
end
