function rx = setupPlutoRx(p)
%SETUPPLUTORX Configure an ADALM-PLUTO receiver for the experiment.

rx = sdrrx('Pluto', ...
    'CenterFrequency',     p.CenterFrequency, ...
    'BasebandSampleRate',  p.SampleRate, ...
    'GainSource',          'Manual', ...
    'Gain',                p.RxGain, ...
    'SamplesPerFrame',     p.SamplesPerFrame, ...
    'OutputDataType',      'double');
end
